version: '3' 
            
services:
    kubernetes_img_1:               
        build: ./kubernetes
        environment:
           - PATH=/Apps/kubernetes/server/bin:$PATH 
        dns:
           - 8.8.8.8   
        network_mode: "host"                
        
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}